name: heroku-website

dependencies:
  - python=3.9
  - pip
  - pip:
      - django
      - django-heroku
      - langdetect
      - gunicorn
      - pillow
      - tensorflow-cpu
      - keras
      - whitenoise
      - pytube==12.1.0
      - protobuf~=3.19.0
