# Generated by Django 4.0.1 on 2022-01-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageFile',
        ),
    ]
