# Generated by Django 4.0.1 on 2022-01-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_rename_image_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='img_file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
