# Generated by Django 4.0.1 on 2022-01-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_imagefile_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='img_name',
            field=models.CharField(max_length=100),
        ),
    ]
